name: comic_creator_dashtoon
description: "A responsive Flutter web app using DashtoonAPI to generate comic images!"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.3.3
  flutter_riverpod: ^2.4.6
  fpdart: ^1.1.0
  fluttertoast: ^8.2.4
  toggle_list: ^0.3.1
  toggle_switch: ^2.1.0
  image_downloader_web: ^2.0.4
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 800
